### ISSUE TITLE
Update Please!

### ISSUE THREAD

**Issue by kotleni** [Kycb42148/MagicMod#6]
**Please update this mod!**

**Comment by Srthmnt** [comment]
I'm working on 2.0

**Comment by qbaddev** [comment]
**Ok**
`work(Srthmnt)`

**Comment by qbaddev** [comment]
**Tip: change the color palette.** She is not very suitable for the game.

**Comment by Kycb42148** [comment]
not working!!! false!!1!!1!1!1!!1!11!!!!1!111 delet this!!!!!!!!111!!1!!1!!
